spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mcp-stateful-server-java
    
  ai:
    mcp:
      server:
        name: mcp-stateful-server-java
        version: 1.0.0
        type: SYNC  # Use SYNC for Streamable HTTP MCP server
        enabled: true  
        stdio: false
        instructions: "This reactive server provides stateful tools for mathematical calculations and file operations with multi-turn conversations"
        protocol: STREAMABLE  # Correct property for Streamable HTTP MCP server
        webflux:
          enabled: false  # Explicitly disable default WebFlux transport
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        streamable-http:
          mcp-endpoint: /mcp  # Default endpoint for MCP Inspector
          keep-alive-interval: 30s  # Optional: enable keep-alive for SSE

logging:
  level:
    com.example.mcpstateful: INFO
    org.springframework.ai: DEBUG
    root: INFO
    
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# CORS configuration for MCP Inspector
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true