spring:
  application:
    name: mcp-stateful-server-java
    
  profiles:
    active: default

logging:
  level:
    com.example.mcpstateful: INFO
    org.springframework.ai.mcp: DEBUG
    org.springframework.web.socket: DEBUG
    root: WARN
    
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# CORS configuration for MCP Inspector
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true